name: Deploy gh-pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build
      run: |
        npm install
        cp -r ./require/@matrixage ./node_modules
        npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./dist
        github_token: ${{ secrets.GITHUB_TOKEN }}
        user_name: ${{ secrets.MY_USER_NAME }}
        user_email: ${{ secrets.MY_USER_EMAIL }}
        commit_message: Update Img